name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: Q-Bug4/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.PROFILE_WAKA_API_KEY }}
          GH_TOKEN: ${{ secrets.PROFILE_ACESS_TOKEN }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
